# Generated by Django 3.2 on 2022-01-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default-img.jpg', upload_to='profile_pics'),
        ),
    ]
